from app.application.entities.flow_step_entity import FlowStep

FLOW_TRIPS_ABROAD = {
    "abroad_0": FlowStep(
        response_key="abroad_travel",
        children=(
            "abroad_1",
            "abroad_2",
            "abroad_3",
            "abroad_4",
            "abroad_5",
        ),
        prev=None,
        next_=None,
        parent=None,
        label="Командировки за границу",
    ),
    "abroad_1": FlowStep(
        response_key="abroad_module",
        children=None,
        prev=None,
        next_="abroad_2",
        parent=None,
        label='👉 1. С чего начать',
    ),
    "abroad_2": FlowStep(
        response_key="abroad_memo",
        children=(
            "abroad_21",
            "abroad_22",
            "abroad_23",
            "abroad_24",
        ),
        prev="abroad_1",
        next_="abroad_21",
        parent="abroad_0",
        label="2. Оформление ДЗ",
    ),
    "abroad_21": FlowStep(
        response_key="abroad_memo_fill",
        children=("abroad_211", "abroad_212", "abroad_213", "abroad_214", "abroad_215",),
        prev="abroad_2",
        next_="abroad_22",
        parent="abroad_2",
        label="2.1. Карточка в модуле",
    ),

    "abroad_211": FlowStep(
        response_key="abroad_memo_fill_name",
        children=None,
        prev=None,
        next_=None,
        parent="abroad_21",
        label="Секция: Инфо о сотруднике",
    ),
    "abroad_212": FlowStep(
        response_key="abroad_memo_fill_trip",
        children=("abroad_2121", "abroad_2122", "abroad_2123", "abroad_2124",),
        prev=None,
        next_=None,
        parent="abroad_21",
        label="Секция: Инфо о командировке",
    ),
    "abroad_2121": FlowStep(
        response_key="abroad_memo_fill_trip_type",
        children=None,
        prev=None,
        next_=None,
        parent="abroad_212",
        label="Поле: Вид командировки",
    ),
    "abroad_2122": FlowStep(
        response_key="abroad_memo_fill_trip_allowance",
        children=None,
        prev=None,
        next_=None,
        parent="abroad_212",
        label="Поле: Желаемый способ...",
    ),
    "abroad_2123": FlowStep(
        response_key="abroad_memo_fill_trip_purpose",
        children=None,
        prev=None,
        next_=None,
        parent="abroad_212",
        label="Поле: Цель командирования",
    ),
    "abroad_2124": FlowStep(
        response_key="abroad_memo_fill_trip_acting",
        children=None,
        prev=None,
        next_=None,
        parent="abroad_212",
        label="Поле: ФИО исп. обяз.",
    ),
    "abroad_213": FlowStep(
        response_key="abroad_memo_fill_route",
        children=None,
        prev=None,
        next_=None,
        parent="abroad_21",
        label="Секция: Маршрут",
    ),

    "abroad_214": FlowStep(
        response_key="abroad_memo_fill_ticket",
        children=None,
        prev=None,
        next_=None,
        parent="abroad_21",
        label="Секция: Транспорт и билеты",
    ),

    "abroad_215": FlowStep(
        response_key="abroad_memo_fill_hotel",
        children=None,
        prev=None,
        next_=None,
        parent="abroad_21",
        label="Секция: Гостиницы",
    ),

    "abroad_22": FlowStep(
        response_key="abroad_memo_upload",
        children=None,
        prev="abroad_21",
        next_="abroad_23",
        parent="abroad_2",
        label='2.2. Выгрузка в СЭД',
    ),
    "abroad_23": FlowStep(
        response_key="abroad_memo_final",
        children=("abroad_231",),
        prev="abroad_22",
        next_="abroad_24",
        parent="abroad_2",
        label='2.3. Дооформление в СЭД',
    ),
    "abroad_231": FlowStep(
        response_key="abroad_memo_final_nuance",
        children=None,
        prev=None,
        next_=None,
        parent="abroad_23",
        label='Прочие нюансы',
    ),
    "abroad_24": FlowStep(
        response_key="abroad_memo_approve",
        children=None,
        prev="abroad_23",
        next_="abroad_3",
        parent="abroad_2",
        label='2.4. Маршрут согласования',
    ),
    "abroad_3": FlowStep(
        response_key="abroad_order",
        children=None,
        prev="abroad_24",
        next_="abroad_4",
        parent=None,
        label="3. Оформление приказа",
    ),
    "abroad_4": FlowStep(
        response_key="abroad_trip",
        children=None,
        prev="abroad_3",
        next_="abroad_5",
        parent=None,
        label="4. В дороге",
    ),
    "abroad_5": FlowStep(
        response_key="abroad_report",
        children=None,
        prev="abroad_4",
        next_=None,
        parent=None,
        label="5. Авансовый отчет",
    ),
}
