from app.application.entities.flow_step_entity import FlowStep

FLOW_TRIPS_HOME = {
    "home_0": FlowStep(
        response_key="home_travel",
        children=(
            "home_1",
            "home_2",
            "home_3",
            "home_4",
            "home_5",
        ),
        prev=None,
        next_=None,
        parent=None,
        label="Командировки по РБ",
    ),
    "home_1": FlowStep(
        response_key="home_module",
        children=None,
        prev=None,
        next_="home_2",
        parent="home_0",
        label='👉 1. С чего начать',
    ),
    "home_2": FlowStep(
        response_key="home_memo",
        children=(
            "home_21",
            "home_22",
            "home_23",
            "home_24",
        ),
        prev="home_1",
        next_="home_21",
        parent="home_0",
        label="2. Оформление заявки",
    ),
    "home_21": FlowStep(
        response_key="home_memo_fill",
        children=("home_211", "home_212", "home_213", "home_214", "home_215", ),
        prev="home_2",
        next_="home_22",
        parent="home_2",
        label="2.1. Карточка в модуле",
    ),

    "home_211": FlowStep(
        response_key="home_memo_fill_name",
        children=None,
        prev=None,
        next_=None,
        parent="home_21",
        label="Секция: Инфо о сотруднике",
    ),
    "home_212": FlowStep(
        response_key="home_memo_fill_trip",
        children=("home_2121", "home_2122", "home_2123", "home_2124", ),
        prev=None,
        next_=None,
        parent="home_21",
        label="Секция: Инфо о командировке",
    ),
    "home_2121": FlowStep(
        response_key="home_memo_fill_trip_type",
        children=None,
        prev=None,
        next_=None,
        parent="home_212",
        label="Поле: Вид командировки",
    ),
    "home_2122": FlowStep(
        response_key="home_memo_fill_trip_allowance",
        children=None,
        prev=None,
        next_=None,
        parent="home_212",
        label="Поле: Желаемый способ...",
    ),
    "home_2123": FlowStep(
        response_key="home_memo_fill_trip_purpose",
        children=None,
        prev=None,
        next_=None,
        parent="home_212",
        label="Поле: Цель командирования",
    ),
    "home_2124": FlowStep(
        response_key="home_memo_fill_trip_acting",
        children=None,
        prev=None,
        next_=None,
        parent="home_212",
        label="Поле: ФИО исп. обяз.",
    ),
    "home_213": FlowStep(
        response_key="home_memo_fill_route",
        children=None,
        prev=None,
        next_=None,
        parent="home_21",
        label="Секция: Маршрут",
    ),

    "home_214": FlowStep(
        response_key="home_memo_fill_ticket",
        children=None,
        prev=None,
        next_=None,
        parent="home_21",
        label="Секция: Транспорт и билеты",
    ),

    "home_215": FlowStep(
        response_key="home_memo_fill_hotel",
        children=None,
        prev=None,
        next_=None,
        parent="home_21",
        label="Секция: Гостиницы",
    ),

    "home_22": FlowStep(
        response_key="home_memo_upload",
        children=None,
        prev="home_21",
        next_="home_23",
        parent="home_2",
        label='2.2. Выгрузка в СЭД',
    ),
    "home_23": FlowStep(
        response_key="home_memo_final",
        children=("home_231", ),
        prev="home_22",
        next_="home_24",
        parent="home_2",
        label='2.3. Дооформление в СЭД',
    ),
    "home_231": FlowStep(
        response_key="home_memo_final_nuance",
        children=None,
        prev=None,
        next_=None,
        parent="home_23",
        label='Прочие нюансы',
    ),
    "home_24": FlowStep(
        response_key="home_memo_approve",
        children=("home_241", "home_242", "home_243", "home_244", ),
        prev="home_23",
        next_="home_3",
        parent="home_2",
        label='2.4. Маршрут согласования',
    ),
    "home_241": FlowStep(
        response_key="home_memo_approve_top",
        children=None,
        prev=None,
        next_=None,
        parent="home_24",
        label='Топ-менеджеры',
    ),
    "home_242": FlowStep(
        response_key="home_memo_approve_dep",
        children=None,
        prev=None,
        next_=None,
        parent="home_24",
        label='Руководители ССП/ПЦП',
    ),
    "home_243": FlowStep(
        response_key="home_memo_approve_rest",
        children=None,
        prev=None,
        next_=None,
        parent="home_24",
        label='Работники ССП/ПЦП',
    ),
    "home_244": FlowStep(
        response_key="home_memo_approve_net",
        children=None,
        prev=None,
        next_=None,
        parent="home_24",
        label='Работники РД/ДО',
    ),
    "home_3": FlowStep(
        response_key="home_order",
        children=None,
        prev="home_24",
        next_="home_4",
        parent=None,
        label="3. Оформление приказа",
    ),
    "home_4": FlowStep(
        response_key="home_trip",
        children=None,
        prev="home_3",
        next_="home_5",
        parent=None,
        label="4. В дороге",
    ),
    "home_5": FlowStep(
        response_key="home_report",
        children=("home_51", "home_52", ),
        prev="home_4",
        next_="home_51",
        parent=None,
        label="5. Авансовый отчет",
    ),
    "home_51": FlowStep(
        response_key="home_report_fill",
        children=("home_511", "home_512", "home_513", ),
        prev="home_5",
        next_="home_52",
        parent="home_5",
        label="Оформление отчета",
    ),
    "home_511": FlowStep(
        response_key="home_report_fill_hotel",
        children=None,
        prev=None,
        next_=None,
        parent="home_51",
        label="Проживание",
    ),
    "home_512": FlowStep(
        response_key="home_report_fill_tickets",
        children=None,
        prev=None,
        next_=None,
        parent="home_51",
        label="Проезд",
    ),
    "home_513": FlowStep(
        response_key="home_report_fill_allowance",
        children=None,
        prev=None,
        next_=None,
        parent="home_51",
        label="Суточные",
    ),
    "home_52": FlowStep(
        response_key="home_report_send",
        children=None,
        prev="home_51",
        next_=None,
        parent="home_5",
        label="Отправка отчета",
    ),
}
